In [2]:
import pandas as p
d = p.read_csv("/Users/sharanyabobbala/Desktop/Assignment 3/ElectronicsData.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (864166034.py, line 2)

In [58]:
d.head(10)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
5,Batteries,$18.99,No Discount,NaN,"Duracell D Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
6,Batteries,$299.99through-$449.99,Special Event - Ends on 01/21/24,NaN,Jackery Explorer 550 Portable Power Station,$,"500W Output Power, 1000W Peak High Power, La..."
7,Batteries,"$1,149.99through-$1,499.99",Special Event - Ends on 01/21/24,NaN,Jackery Explorer 2000 Pro Portable Power Station,$,"2220W Output Power, 4400W Peak High Power, L..."
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...

In [60]:
print(d.loc[4])#reading specific row

Sub Category                                            Batteries
Price                                                     $14.99
Discount                                              No Discount
Rating             Rated 4.8 out of 5 stars based on 125 reviews.
Title              Duracell 2032 Lithium Coin Batteries, 12-count
Currency                                                        $
Feature         Our Longest Lasting Lithium Coin Battery Ever ...
Name: 4, dtype: object

In [62]:
print(d.loc[10:15,['Sub Category','Price']])

               Sub Category     Price
10     Cameras & Camcorders  $429.99
11     Cameras & Camcorders  $239.97
12     Cameras & Camcorders  $349.99
13     Cameras & Camcorders  $839.99
14     Cameras & Camcorders  $849.99
15  Desktop Computers & PCs  $649.99

In [17]:
print(d.loc[:15,['Sub Category','Title','Rating']])

               Sub Category  \
0                 Batteries
1                 Batteries
2                 Batteries
3                 Batteries
4                 Batteries
5                 Batteries
6                 Batteries
7                 Batteries
8      Cameras & Camcorders
9      Cameras & Camcorders
10     Cameras & Camcorders
11     Cameras & Camcorders
12     Cameras & Camcorders
13     Cameras & Camcorders
14     Cameras & Camcorders
15  Desktop Computers & PCs

                                                Title  \
0   Duracell Coppertop Alkaline AA Batteries, 40-c...
1   Duracell Coppertop Alkaline AAA Batteries, 40-...
2             Duracell 9V Alkaline Batteries, 8-count
3             Duracell C Alkaline Batteries, 14-count
4      Duracell 2032 Lithium Coin Batteries, 12-count
5             Duracell D Alkaline Batteries, 14-count
6         Jackery Explorer 550 Portable Power Station
7    Jackery Explorer 2000 Pro Portable Power Station
8             GoPro HERO11 Black Action Camera Bundle
9   Insta360 X3 - 5.7K 360° Action Camera Adventur...
10              DJI Mini 3 Drone Aerial Camera Bundle
11            GoPro HERO10 Black Action Camera Bundle
12                 Insta360 GO 3 Action Camera Bundle
13                        DJI Mini 3 Pro Drone Bundle
14  Autel Robotics - EVO Lite+ Premium Bundle - Dr...
15  Lenovo IdeaCentre 3i Desktop - 13th Gen Intel ...

                                            Rating
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4   Rated 4.8 out of 5 stars based on 125 reviews.
5                                              NaN
6                                              NaN
7                                              NaN
8   Rated 4.2 out of 5 stars based on 238 reviews.
9    Rated 4.4 out of 5 stars based on 99 reviews.
10  Rated 4.4 out of 5 stars based on 115 reviews.
11  Rated 4.1 out of 5 stars based on 311 reviews.
12   Rated 3.6 out of 5 stars based on 11 reviews.
13  Rated 4.5 out of 5 stars based on 418 reviews.
14   Rated 4.3 out of 5 stars based on 49 reviews.
15  Rated 4.5 out of 5 stars based on 128 reviews.

In [64]:
print(d.loc[20:24,['Sub Category','Currency','Price']])

               Sub Category Currency       Price
20  Desktop Computers & PCs        $  $1,399.99
21  Desktop Computers & PCs        $    $599.99
22  Desktop Computers & PCs        $  $1,249.99
23  Desktop Computers & PCs        $  $1,099.99
24  Desktop Computers & PCs        $    $999.99

In [66]:
c = d.loc[:, ['Sub Category']]#reading specific column
print(c)

               Sub Category
0                 Batteries
1                 Batteries
2                 Batteries
3                 Batteries
4                 Batteries
..                      ...
638  Video Games & Consoles
639  Video Games & Consoles
640  Video Games & Consoles
641  Video Games & Consoles
642  Video Games & Consoles

[643 rows x 1 columns]

In [68]:
d1 = p.read_excel("/Users/sharanyabobbala/Desktop/Assignment 3/AmazonBooks.xlsx")

In [70]:
print(d1)

                                                  Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
595  Live Free Or Die: America (and the World) on t...
596                                 Burn After Writing
597  Get Out of Your Head: Stopping the Spiral of T...
598  Human Body Activity Book for Kids: Hands-On Fu...
599                                 Educated: A Memoir

                       Author  User Rating  Reviews  Price  Year        Genre
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
595              Sean Hannity          4.8    20153     15  2020  Non Fiction
596              Sharon Jones          4.6    26423      8  2020  Non Fiction
597              Jennie Allen          4.7    12879     14  2020  Non Fiction
598              Katie Stokes          4.7    14128      5  2020  Non Fiction
599            Tara Westover           4.7    45351     11  2020  Non Fiction

[600 rows x 7 columns]

In [92]:
d1.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [72]:
print(d1.loc[7])#reading specific row

Name           A Gentleman in Moscow: A Novel
Author                            Amor Towles
User Rating                               4.7
Reviews                                 19699
Price                                      15
Year                                     2017
Genre                                 Fiction
Name: 7, dtype: object

In [76]:
c1 = d1.loc[:, ['Author']]#reading specific column
print(c1)

                       Author
0                    JJ Smith
1                Stephen King
2          Jordan B. Peterson
3               George Orwell
4    National Geographic Kids
..                        ...
595              Sean Hannity
596              Sharon Jones
597              Jennie Allen
598              Katie Stokes
599            Tara Westover

[600 rows x 1 columns]

In [90]:
print (d1.loc[[41,79,8],['Author','Name']])# multi-axes indexing funtion

             Author                                           Name
41  Bill Martin Jr.       Brown Bear, Brown Bear, What Do You See?
79     Stephen King                          Doctor Sleep: A Novel
8       James Comey  A Higher Loyalty: Truth, Lies, and Leadership

In [94]:
print (d1.loc[[41,79,8],['Author','User Rating']])# multi-axes indexing funtion

             Author  User Rating
41  Bill Martin Jr.          4.9
79     Stephen King          4.7
8       James Comey          4.7

In [111]:
import pandas as pd
with pd.ExcelFile('/Users/sharanyabobbala/Desktop/Assignment 3/UPDOWND.xlsx') as xls:
    df1=pd.read_excel(xls, 'Sheet1')
    df2=pd.read_excel(xls, 'Sheet2')

ValueError: Worksheet named 'Sheet2' not found